export const apis = {
  //POST ENDPOINTS
  signUp: 'api/v1/signup',
  login: 'api/v1/login',
  otp: 'api/v1/verifyOtp',
  resendOtp: 'api/v1/resendotp',
  loginWithGoogle: 'api/v1/firebase',
  createPost : 'api/v1/createNewPost',
  getYudios : 'api/v1/getYudio',
  getMoments : 'api/v1/getMoments',
  getDocuments : 'api/v1/getUserPost',
  forgotPassword : 'api/v1/forgotPassword',
  verifyForgetPassword : 'api/v1/verifyPasswordToken',
  resetPassword : 'api/v1/resetPassword',
  getPosts : 'api/v1/getPost',
  getUsers : 'api/v1/getUsers',
  like  : 'api/v1/likePost',
  comment : 'api/v1/addComment',
  getFollower : 'api/v1/getFollowing/',
  reactOnComment : 'api/v1/reactoncomment',
  replyOnComment : 'api/v1/replyoncomment',
  getStories : 'api/v1/getStory',
  getAllHighlight : 'api/v1/post/getAllHighlight',
  updateProfile : 'api/v1/profile/update',
  savePost : "api/v1/post/save",
  repost : "api/v1/sharePost",
  createNewHighlight : 'api/v1/post/createHighlight',
  createCategory : 'api/v1/post/album',
  //GET ENDPOINTS
  getNotification:'api/v1/notification',
  getContactSuggestions : 'api/v1/contactSuggetion',
  follow : 'api/v1/follow',
  unfollow : 'api/v1/unfollow',
  addInterest : 'api/v1/user/intrest',
  generateWaveforms : 'api/v1/generateWaveForms',
  getChats : 'api/v1/chats',
  getMessages : 'api/v1/messages',
  getProfile : 'api/v1/profile',
  getAllInterests : 'api/v1/intrest',
  getOnBoardingContent : 'api/v1/onboarding',
  getSavedPosts : 'api/v1/post/saved',
  getAlbums : 'api/v1/post/album',
  getFollowing : 'api/v1/getFollower',
  // DELETE ENDPOINTS
  // PATCH ENDPOINTS
};
